/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Bus;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Anudeep
 */
public class AdminRouteMgtGUI extends javax.swing.JFrame {

    /**
     * Creates new form AdminRouteMgtGUI
     */
    String ausername;
    int busId;
    Bus bus = new Bus();
    public AdminRouteMgtGUI(String ausername) {
        super("Route Management");
        initComponents();
        //setSize(1350,730);
        this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        this.ausername = ausername;
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        routeIDLbl = new javax.swing.JLabel();
        routeIDtxt = new javax.swing.JTextField();
        editButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        logOutButton1 = new javax.swing.JButton();
        addroutebtn = new javax.swing.JButton();
        allRoutesButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        usermgtBtn = new javax.swing.JButton();
        routemgtBtn = new javax.swing.JButton();
        balanceshtBtn = new javax.swing.JButton();
        ticketSearchBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        routeIDLbl.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        routeIDLbl.setText("Route ID");

        routeIDtxt.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        routeIDtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                routeIDtxtActionPerformed(evt);
            }
        });

        editButton.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        editButton.setText("Edit/Delete");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        resetButton.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        logOutButton1.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        logOutButton1.setText("Log Out");
        logOutButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButton1ActionPerformed(evt);
            }
        });

        addroutebtn.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        addroutebtn.setText("Add Route");
        addroutebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addroutebtnActionPerformed(evt);
            }
        });

        allRoutesButton.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        allRoutesButton.setText("All Routes");
        allRoutesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allRoutesButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(330, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logOutButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(routeIDLbl)
                                .addGap(18, 18, 18)
                                .addComponent(routeIDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(addroutebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(allRoutesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(315, Short.MAX_VALUE))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addroutebtn)
                    .addComponent(allRoutesButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(routeIDLbl)
                    .addComponent(routeIDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editButton)
                    .addComponent(resetButton))
                .addGap(180, 180, 180)
                .addComponent(logOutButton1)
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        usermgtBtn.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        usermgtBtn.setText("User Management");
        usermgtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usermgtBtnActionPerformed(evt);
            }
        });

        routemgtBtn.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        routemgtBtn.setText("Route Management");
        routemgtBtn.setEnabled(false);

        balanceshtBtn.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        balanceshtBtn.setText("Balance Sheet");
        balanceshtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balanceshtBtnActionPerformed(evt);
            }
        });

        ticketSearchBtn.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        ticketSearchBtn.setText("Ticket Search");
        ticketSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ticketSearchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(usermgtBtn)
                .addGap(18, 18, 18)
                .addComponent(routemgtBtn)
                .addGap(18, 18, 18)
                .addComponent(balanceshtBtn)
                .addGap(18, 18, 18)
                .addComponent(ticketSearchBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usermgtBtn)
                    .addComponent(balanceshtBtn)
                    .addComponent(routemgtBtn)
                    .addComponent(ticketSearchBtn))
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void routeIDtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_routeIDtxtActionPerformed
        // TODO add your handling code here:
        editButtonActionPerformed(evt);
    }//GEN-LAST:event_routeIDtxtActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        busId = Integer.parseInt(routeIDtxt.getText());
        if(busId==0){
            JOptionPane.showMessageDialog(this, "Enter a routeId");
        }
        else if(bus.getSource(busId)==null){
            JOptionPane.showMessageDialog(this, "Enter a valid routeId");
        }
        else{ 
            EditRouteGUI editRouteGUI = new EditRouteGUI(ausername,busId);
            this.setVisible(false);
            editRouteGUI.setVisible(true);
        }
    }//GEN-LAST:event_editButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        routeIDtxt.setText("");
    }//GEN-LAST:event_resetButtonActionPerformed

    private void logOutButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButton1ActionPerformed
        // TODO add your handling code here:
        AdminLoginGUI adminLoginGUI = new AdminLoginGUI();
        this.setVisible(false);
        adminLoginGUI.setVisible(true);
    }//GEN-LAST:event_logOutButton1ActionPerformed

    private void addroutebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addroutebtnActionPerformed
        // TODO add your handling code here:
        
        AddRouteGUI addRouteGUI = new AddRouteGUI(ausername);
        this.setVisible(false);
        addRouteGUI.setVisible(true);
    }//GEN-LAST:event_addroutebtnActionPerformed

    private void usermgtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usermgtBtnActionPerformed
        // TODO add your handling code here:
        AdminUserMgtGUI adminUserMgtGUI = new AdminUserMgtGUI(ausername);
        this.setVisible(false);
        adminUserMgtGUI.setVisible(true);
    }//GEN-LAST:event_usermgtBtnActionPerformed

    private void balanceshtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balanceshtBtnActionPerformed
        // TODO add your handling code here:
        BalanceSheetGUI balanceSheetGUI = new BalanceSheetGUI(ausername);
        this.setVisible(false);
        balanceSheetGUI.setVisible(true);
    }//GEN-LAST:event_balanceshtBtnActionPerformed

    private void allRoutesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allRoutesButtonActionPerformed
        // TODO add your handling code here:
        AllRoutesGUI allRoutesGUI = new AllRoutesGUI(ausername);
        this.setVisible(false);
        allRoutesGUI.setVisible(true);
    }//GEN-LAST:event_allRoutesButtonActionPerformed

    private void ticketSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ticketSearchBtnActionPerformed
        // TODO add your handling code here:
        TicketSearchGUI ticketSearchGUI = new TicketSearchGUI(ausername);
        this.setVisible(false);
        ticketSearchGUI.setVisible(true);
    }//GEN-LAST:event_ticketSearchBtnActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addroutebtn;
    private javax.swing.JButton allRoutesButton;
    private javax.swing.JButton balanceshtBtn;
    private javax.swing.JButton editButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JButton logOutButton1;
    private javax.swing.JButton resetButton;
    private javax.swing.JLabel routeIDLbl;
    private javax.swing.JTextField routeIDtxt;
    private javax.swing.JButton routemgtBtn;
    private javax.swing.JButton ticketSearchBtn;
    private javax.swing.JButton usermgtBtn;
    // End of variables declaration//GEN-END:variables
}
