/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.BusObj;
import Model.Bus;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Anudeep
 */
public class AllRoutesGUI extends javax.swing.JFrame {

    /**
     * Creates new form AllRoutesGUI
     */
    String ausername;
    BusObj busobj;
    Bus bus = new Bus();
    int i;
    public AllRoutesGUI(String ausername) {
        super("All Routes");
        initComponents();
        this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        this.ausername = ausername;
        busobj = bus.getAllRoutes();
        String[] cols = {"Bus ID","Source","Departure Time","Destination","Arrival Time","Price"};
        DefaultTableModel table = new DefaultTableModel(cols,0);
        backButton.setModel(table);
            
        for(i = 0;i<busobj.busid.size();i++){
            Object[] data = {busobj.busid.get(i),busobj.source.get(i),busobj.departureTime.get(i),busobj.destination.get(i),busobj.arrivalTime.get(i),busobj.price.get(i)};
               
            table.addRow(data);
        }
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        usermgtBtn = new javax.swing.JButton();
        routemgtBtn = new javax.swing.JButton();
        balanceshtBtn = new javax.swing.JButton();
        ticketSearchBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        backButton = new javax.swing.JTable();
        submitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        usermgtBtn.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        usermgtBtn.setText("User Management");
        usermgtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usermgtBtnActionPerformed(evt);
            }
        });

        routemgtBtn.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        routemgtBtn.setText("Route Management");
        routemgtBtn.setEnabled(false);

        balanceshtBtn.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        balanceshtBtn.setText("Balance Sheet");
        balanceshtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balanceshtBtnActionPerformed(evt);
            }
        });

        ticketSearchBtn.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        ticketSearchBtn.setText("Ticket Search");
        ticketSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ticketSearchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(usermgtBtn)
                .addGap(18, 18, 18)
                .addComponent(routemgtBtn)
                .addGap(18, 18, 18)
                .addComponent(balanceshtBtn)
                .addGap(18, 18, 18)
                .addComponent(ticketSearchBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usermgtBtn)
                    .addComponent(routemgtBtn)
                    .addComponent(balanceshtBtn)
                    .addComponent(ticketSearchBtn))
                .addGap(50, 50, 50))
        );

        backButton.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        backButton.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Route ID", "Source", "Departure Time", "Destination", "Destination Time", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        backButton.setEnabled(false);
        jScrollPane1.setViewportView(backButton);

        submitButton.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        submitButton.setText("Back");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(submitButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(submitButton))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usermgtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usermgtBtnActionPerformed
        // TODO add your handling code here:
        AdminUserMgtGUI adminUserMgtGUI = new AdminUserMgtGUI(ausername);
        this.setVisible(false);
        adminUserMgtGUI.setVisible(true);
    }//GEN-LAST:event_usermgtBtnActionPerformed

    private void balanceshtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balanceshtBtnActionPerformed
        // TODO add your handling code here:
        BalanceSheetGUI balanceSheetGUI = new BalanceSheetGUI(ausername);
        this.setVisible(false);
        balanceSheetGUI.setVisible(true);
    }//GEN-LAST:event_balanceshtBtnActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        AdminRouteMgtGUI adminRouteMgtGUI = new AdminRouteMgtGUI(ausername);
        this.setVisible(false);
        adminRouteMgtGUI.setVisible(true);
    }//GEN-LAST:event_submitButtonActionPerformed

    private void ticketSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ticketSearchBtnActionPerformed
        // TODO add your handling code here:
        TicketSearchGUI ticketSearchGUI = new TicketSearchGUI(ausername);
        this.setVisible(false);
        ticketSearchGUI.setVisible(true);
    }//GEN-LAST:event_ticketSearchBtnActionPerformed

    /**
     * @param args the command line arguments
     */
   
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable backButton;
    private javax.swing.JButton balanceshtBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton routemgtBtn;
    private javax.swing.JButton submitButton;
    private javax.swing.JButton ticketSearchBtn;
    private javax.swing.JButton usermgtBtn;
    // End of variables declaration//GEN-END:variables
}
