/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.BalanceSheetObj;
import Model.Ticket;
import java.util.Calendar;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Anudeep
 */
public class BalanceSheetGUI extends javax.swing.JFrame {

    /**
     * Creates new form BalanceSheetGUI
     */
    String ausername;
    BalanceSheetObj bsobj;

    Ticket ticket = new Ticket();
    public BalanceSheetGUI(String ausername) {
        super("Balance Sheet");
        initComponents();
        //setSize(1350,730);
        this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        this.ausername = ausername;
        Calendar min1 = Calendar.getInstance();
        min1.add(Calendar.DAY_OF_MONTH, -30);
        Calendar max1 = Calendar.getInstance();
        max1.add(Calendar.DAY_OF_MONTH, 30);
        fromDate.setSelectableDateRange(min1.getTime(), max1.getTime());
        toDate.setSelectableDateRange(min1.getTime(), max1.getTime());
        fromDate.setDate(Calendar.getInstance().getTime());
        toDate.setDate(Calendar.getInstance().getTime());
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        usermgtBtn = new javax.swing.JButton();
        routemgtBtn = new javax.swing.JButton();
        retrivetcktbtn = new javax.swing.JButton();
        ticketSearchBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        fromLbl = new javax.swing.JLabel();
        fromDate = new com.toedter.calendar.JDateChooser();
        toLbl = new javax.swing.JLabel();
        toDate = new com.toedter.calendar.JDateChooser();
        generateBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        logOutButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 700));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        usermgtBtn.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        usermgtBtn.setText("User Management");
        usermgtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usermgtBtnActionPerformed(evt);
            }
        });

        routemgtBtn.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        routemgtBtn.setText("Route Management");
        routemgtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                routemgtBtnActionPerformed(evt);
            }
        });

        retrivetcktbtn.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        retrivetcktbtn.setText("Balance Sheet");
        retrivetcktbtn.setEnabled(false);

        ticketSearchBtn.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        ticketSearchBtn.setText("Ticket Search");
        ticketSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ticketSearchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(usermgtBtn)
                .addGap(18, 18, 18)
                .addComponent(routemgtBtn)
                .addGap(18, 18, 18)
                .addComponent(retrivetcktbtn)
                .addGap(18, 18, 18)
                .addComponent(ticketSearchBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usermgtBtn)
                    .addComponent(routemgtBtn)
                    .addComponent(retrivetcktbtn)
                    .addComponent(ticketSearchBtn))
                .addGap(37, 37, 37))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        fromLbl.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        fromLbl.setText("From");

        toLbl.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        toLbl.setText("To");

        generateBtn.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        generateBtn.setText("Generate");
        generateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateBtnActionPerformed(evt);
            }
        });

        resetBtn.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fromLbl)
                .addGap(18, 18, 18)
                .addComponent(fromDate, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(toLbl)
                .addGap(18, 18, 18)
                .addComponent(toDate, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(generateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(generateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(fromLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fromDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(toLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(toDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ticket ID", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setEnabled(false);
        jScrollPane1.setViewportView(jTable1);

        logOutButton1.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        logOutButton1.setText("Log Out");
        logOutButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(logOutButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(logOutButton1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateBtnActionPerformed
        // TODO add your handling code here:
        int i;
        if(fromDate.getDate().compareTo(toDate.getDate())>0){
            JOptionPane.showMessageDialog(this, "To date must be after from date.");            
        }
        else{
            bsobj = ticket.getBalanceSheet(fromDate.getDate(), toDate.getDate());
            
            String[] cols = {"Ticket ID","Price"};
            DefaultTableModel table = new DefaultTableModel(cols,0);
            jTable1.setModel(table);
            
            for(i = 0;i<bsobj.tid.size()-1;i++){
               Object[] data = {bsobj.tid.get(i),bsobj.price1.get(i)};
               
               table.addRow(data);
            }
            Object[] data = {"Total",bsobj.price1.get(i)};
            table.addRow(data);
            
            
            
            
        }
    }//GEN-LAST:event_generateBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        // TODO add your handling code here:
        Calendar min1 = Calendar.getInstance();
        min1.add(Calendar.DAY_OF_MONTH, -30);
        Calendar max1 = Calendar.getInstance();
        max1.add(Calendar.DAY_OF_MONTH, 0);
        fromDate.setDate(max1.getTime());
        toDate.setDate(max1.getTime());
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
    }//GEN-LAST:event_resetBtnActionPerformed

    private void logOutButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButton1ActionPerformed
        // TODO add your handling code here:
        AdminLoginGUI adminLoginGUI = new AdminLoginGUI();
        this.setVisible(false);
        adminLoginGUI.setVisible(true);
    }//GEN-LAST:event_logOutButton1ActionPerformed

    private void usermgtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usermgtBtnActionPerformed
        // TODO add your handling code here:
        AdminUserMgtGUI adminUserMgtGUI = new AdminUserMgtGUI(ausername);
        this.setVisible(false);
        adminUserMgtGUI.setVisible(true);
    }//GEN-LAST:event_usermgtBtnActionPerformed

    private void routemgtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_routemgtBtnActionPerformed
        // TODO add your handling code here:
        AdminRouteMgtGUI adminRouteMgtGUI = new AdminRouteMgtGUI(ausername);
        this.setVisible(false);
        adminRouteMgtGUI.setVisible(true);
    }//GEN-LAST:event_routemgtBtnActionPerformed

    private void ticketSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ticketSearchBtnActionPerformed
        // TODO add your handling code here:
        TicketSearchGUI ticketSearchGUI = new TicketSearchGUI(ausername);
        this.setVisible(false);
        ticketSearchGUI.setVisible(true);
        
    }//GEN-LAST:event_ticketSearchBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser fromDate;
    private javax.swing.JLabel fromLbl;
    private javax.swing.JButton generateBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton logOutButton1;
    private javax.swing.JButton resetBtn;
    private javax.swing.JButton retrivetcktbtn;
    private javax.swing.JButton routemgtBtn;
    private javax.swing.JButton ticketSearchBtn;
    private com.toedter.calendar.JDateChooser toDate;
    private javax.swing.JLabel toLbl;
    private javax.swing.JButton usermgtBtn;
    // End of variables declaration//GEN-END:variables
}
