/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Bus;
import java.util.Calendar;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;

/**
 *
 * @author Anudeep
 */
public class BookTicketGUI extends javax.swing.JFrame {

    /**
     * Creates new form BookTicketGUI
     */
    Bus bus = new Bus();
    String username;
    String source;
    String destination;
    String depttime;
    Date date;
    int busId;
    public BookTicketGUI(String username) {
        super("Book Ticket");
        initComponents();
        //setSize(1350, 730);
        this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        Calendar min1 = Calendar.getInstance();
        min1.add(Calendar.DAY_OF_MONTH, 1);
        Calendar max1 = Calendar.getInstance();
        max1.add(Calendar.DAY_OF_MONTH, 31);
        bookdatechooser.setSelectableDateRange(min1.getTime(), max1.getTime());
        bookdatechooser.setDate(min1.getTime());
        DefaultComboBoxModel model = new DefaultComboBoxModel( bus.source().toArray() );
        srccombo.setModel( model );
        this.username = username;
        
        
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        booktcktbtn = new javax.swing.JButton();
        cncltcktbtn = new javax.swing.JButton();
        retrivetcktbtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        srclbl = new javax.swing.JLabel();
        srccombo = new javax.swing.JComboBox<>();
        destlbl = new javax.swing.JLabel();
        destcombo = new javax.swing.JComboBox<>();
        destlbl1 = new javax.swing.JLabel();
        bookdatechooser = new com.toedter.calendar.JDateChooser();
        submitButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        logOutButton1 = new javax.swing.JButton();
        depttimelbl = new javax.swing.JLabel();
        deptcombo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        booktcktbtn.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        booktcktbtn.setText("Book Ticket");
        booktcktbtn.setEnabled(false);

        cncltcktbtn.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        cncltcktbtn.setText("Cancel Ticket");
        cncltcktbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cncltcktbtnActionPerformed(evt);
            }
        });

        retrivetcktbtn.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        retrivetcktbtn.setText("Retrive Ticket");
        retrivetcktbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retrivetcktbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(booktcktbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cncltcktbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(retrivetcktbtn)
                .addGap(70, 70, 70))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(booktcktbtn)
                    .addComponent(cncltcktbtn)
                    .addComponent(retrivetcktbtn))
                .addGap(45, 45, 45))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        srclbl.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        srclbl.setText("Source");

        srccombo.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        srccombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srccomboActionPerformed(evt);
            }
        });

        destlbl.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        destlbl.setText("Destination");

        destcombo.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        destcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destcomboActionPerformed(evt);
            }
        });

        destlbl1.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        destlbl1.setText("Date");

        submitButton.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        resetButton.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        logOutButton1.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        logOutButton1.setText("Log Out");
        logOutButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButton1ActionPerformed(evt);
            }
        });

        depttimelbl.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        depttimelbl.setText("Departure Time");

        deptcombo.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        deptcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deptcomboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(submitButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(destlbl1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(srclbl, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(srccombo, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(destlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(bookdatechooser, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(destcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(depttimelbl)
                        .addGap(18, 18, 18)
                        .addComponent(deptcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logOutButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(srclbl)
                    .addComponent(srccombo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(destlbl)
                    .addComponent(destcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(depttimelbl)
                    .addComponent(deptcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(destlbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bookdatechooser, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                .addComponent(logOutButton1)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void srccomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srccomboActionPerformed
        // TODO add your handling code here:
        
        source = (String) srccombo.getSelectedItem();
        DefaultComboBoxModel model = new DefaultComboBoxModel( bus.destination(source).toArray());
        destcombo.setModel( model );
        
    }//GEN-LAST:event_srccomboActionPerformed

    private void destcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destcomboActionPerformed
        // TODO add your handling code here:
        source = (String) srccombo.getSelectedItem();
        destination = (String)destcombo.getSelectedItem();
        DefaultComboBoxModel model = new DefaultComboBoxModel( bus.departuretime(source,destination).toArray());
        deptcombo.setModel( model );
    }//GEN-LAST:event_destcomboActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        source = (String) srccombo.getSelectedItem();
        destination = (String) destcombo.getSelectedItem();
        depttime = (String) deptcombo.getSelectedItem();
        date = bookdatechooser.getDate();
        busId = bus.busSelect(source, destination, depttime, date);
        
        BusLayoutGUI busLayoutGUI = new BusLayoutGUI(username,busId,date);
        this.setVisible(false);
        busLayoutGUI.setVisible(true);
               
        
    }//GEN-LAST:event_submitButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        Calendar min1 = Calendar.getInstance();
        min1.add(Calendar.DAY_OF_MONTH, 1);
        bookdatechooser.setDate(min1.getTime());
    }//GEN-LAST:event_resetButtonActionPerformed

    private void logOutButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButton1ActionPerformed
        // TODO add your handling code here:
        HomeGUI homeGUI = new HomeGUI();
        this.setVisible(false);
        homeGUI.setVisible(true);
    }//GEN-LAST:event_logOutButton1ActionPerformed

    private void cncltcktbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cncltcktbtnActionPerformed
        // TODO add your handling code here:
        CancelHomeGUI cancelHomeGUI = new CancelHomeGUI(username);
        this.setVisible(false);
        cancelHomeGUI.setVisible(true);
                
    }//GEN-LAST:event_cncltcktbtnActionPerformed

    private void retrivetcktbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retrivetcktbtnActionPerformed
        // TODO add your handling code here:
        RetriveTicketGUI retriveTicketGUI = new RetriveTicketGUI(username);
        this.setVisible(false);
        retriveTicketGUI.setVisible(true);
    }//GEN-LAST:event_retrivetcktbtnActionPerformed

    private void deptcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deptcomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deptcomboActionPerformed

    /**
     * @param args the command line arguments
     */
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser bookdatechooser;
    private javax.swing.JButton booktcktbtn;
    private javax.swing.JButton cncltcktbtn;
    private javax.swing.JComboBox<String> deptcombo;
    private javax.swing.JLabel depttimelbl;
    private javax.swing.JComboBox<String> destcombo;
    private javax.swing.JLabel destlbl;
    private javax.swing.JLabel destlbl1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton logOutButton1;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton retrivetcktbtn;
    private javax.swing.JComboBox<String> srccombo;
    private javax.swing.JLabel srclbl;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
