/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.*;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.*;



/**
 *
 * @author Anudeep
 */
public class BusLayoutGUI extends javax.swing.JFrame {

    /**
     * Creates new form BusLayoutGUI
     */
    JButton seat[];
    String username;
    int busId;
    Date date;
    String name;
    String source;
    String destination;
    String arrivaltime;
    String departuretime;
    double amount;
    int seatno;
    int ticketno;
    Bus bus = new Bus();
    Home home = new Home();
    Ticket ticket = new Ticket();
    ArrayList<Integer> bseats;
    public BusLayoutGUI(String username, int busId, Date date) {
        super("Select Seat");
        initComponents();
        //setSize(1350, 730);
        this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        this.username = username;
        this.busId = busId;
        this.date = date;
        source = bus.getSource(busId);
        srctxt.setText(source);
        destination = bus.getDestination(busId);
        desttxt.setText(destination);
        arrivaltime = bus.getArrivalTime(busId);
        arvltimetxt.setText(arrivaltime);
        departuretime = bus.getDepartureTime(busId);
        depttimetxt.setText(departuretime);
        amount = bus.getAmount(busId);
        amttxt.setText(Double.toString(amount));
        name = home.getName(username);
        nametxt.setText(name);
        datetxt.setDate(date);
        bseats = ticket.bookedSeats(busId, date);
               
        seat = new JButton[21];
        for(int i = 0; i < 21; i++){
            seat[i] = new JButton(String.valueOf(i+1));
            seat[i].setSize(5, 5);
            jPanel3.add(seat[i]);
            for(int j =0; j<bseats.size();j++){
                if(bseats.get(j)==i+1)
                    seat[i].setEnabled(false);
            }
            
            addActionListenerTo(seat[i],i);      
        }
        
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        booktcktbtn = new javax.swing.JButton();
        cncltcktbtn = new javax.swing.JButton();
        retrivetcktbtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        srclbl = new javax.swing.JLabel();
        srctxt = new javax.swing.JTextField();
        destlbl = new javax.swing.JLabel();
        desttxt = new javax.swing.JTextField();
        depttimelbl = new javax.swing.JLabel();
        depttimetxt = new javax.swing.JTextField();
        arvltimelbl = new javax.swing.JLabel();
        arvltimetxt = new javax.swing.JTextField();
        datelbl = new javax.swing.JLabel();
        namelbl = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        amtlbl = new javax.swing.JLabel();
        amttxt = new javax.swing.JTextField();
        seatlbl = new javax.swing.JLabel();
        seattxt = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        confirmButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        logOutButton1 = new javax.swing.JButton();
        datetxt = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        booktcktbtn.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        booktcktbtn.setText("Book Ticket");
        booktcktbtn.setEnabled(false);

        cncltcktbtn.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        cncltcktbtn.setText("Cancel Ticket");
        cncltcktbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cncltcktbtnActionPerformed(evt);
            }
        });

        retrivetcktbtn.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        retrivetcktbtn.setText("Retrive Ticket");
        retrivetcktbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retrivetcktbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(booktcktbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 344, Short.MAX_VALUE)
                .addComponent(cncltcktbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 344, Short.MAX_VALUE)
                .addComponent(retrivetcktbtn)
                .addGap(70, 70, 70))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(booktcktbtn)
                    .addComponent(cncltcktbtn)
                    .addComponent(retrivetcktbtn))
                .addGap(45, 45, 45))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        srclbl.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        srclbl.setText("Source");

        srctxt.setEditable(false);
        srctxt.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        srctxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srctxtActionPerformed(evt);
            }
        });

        destlbl.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        destlbl.setText("Destination");

        desttxt.setEditable(false);
        desttxt.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        desttxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desttxtActionPerformed(evt);
            }
        });

        depttimelbl.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        depttimelbl.setText("Departure Time");

        depttimetxt.setEditable(false);
        depttimetxt.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        depttimetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depttimetxtActionPerformed(evt);
            }
        });

        arvltimelbl.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        arvltimelbl.setText("Arrival Time");

        arvltimetxt.setEditable(false);
        arvltimetxt.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        arvltimetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arvltimetxtActionPerformed(evt);
            }
        });

        datelbl.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        datelbl.setText("Date");

        namelbl.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        namelbl.setText("Name");

        nametxt.setEditable(false);
        nametxt.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        nametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nametxtActionPerformed(evt);
            }
        });

        amtlbl.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        amtlbl.setText("Amount");

        amttxt.setEditable(false);
        amttxt.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        amttxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amttxtActionPerformed(evt);
            }
        });

        seatlbl.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        seatlbl.setText("Seat");

        seattxt.setEditable(false);
        seattxt.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        seattxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seattxtActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.setLayout(new java.awt.GridLayout(7, 3, 3, 5));

        confirmButton.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        confirmButton.setText("Confirm");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        resetButton.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        backButton.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        logOutButton1.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        logOutButton1.setText("Log Out");
        logOutButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButton1ActionPerformed(evt);
            }
        });

        datetxt.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(amtlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(39, 39, 39)
                                    .addComponent(amttxt))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(srclbl, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(destlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(datelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(39, 39, 39)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(srctxt)
                                        .addComponent(desttxt)
                                        .addComponent(datetxt, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)))))
                        .addGap(183, 183, 183)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(depttimelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(depttimetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(arvltimelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(arvltimetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(namelbl, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(seatlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(seattxt, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logOutButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(logOutButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(srclbl)
                            .addComponent(srctxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(depttimelbl)
                            .addComponent(depttimetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(destlbl)
                            .addComponent(desttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(arvltimelbl)
                            .addComponent(arvltimetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(datelbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(datetxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(amtlbl)
                            .addComponent(amttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(namelbl)
                            .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(seatlbl)
                            .addComponent(seattxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(98, 98, 98))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addActionListenerTo(JButton seat, int i)
    {
     seat.addActionListener( e -> {
         seattxt.setText(Integer.toString(i+1));
     }
     );   
    }
    
    
    
    
    private void srctxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srctxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_srctxtActionPerformed

    private void desttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desttxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desttxtActionPerformed

    private void depttimetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depttimetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_depttimetxtActionPerformed

    private void arvltimetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arvltimetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arvltimetxtActionPerformed

    private void nametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nametxtActionPerformed

    private void amttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amttxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amttxtActionPerformed

    private void cncltcktbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cncltcktbtnActionPerformed
        // TODO add your handling code here:
        CancelHomeGUI cancelHomeGUI = new CancelHomeGUI(username);
        this.setVisible(false);
        cancelHomeGUI.setVisible(true);
    }//GEN-LAST:event_cncltcktbtnActionPerformed

    private void retrivetcktbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retrivetcktbtnActionPerformed
        // TODO add your handling code here:
        RetriveTicketGUI retriveTicketGUI = new RetriveTicketGUI(username);
        this.setVisible(false);
        retriveTicketGUI.setVisible(true);
    }//GEN-LAST:event_retrivetcktbtnActionPerformed

    private void seattxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seattxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seattxtActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        BookTicketGUI bookTicketGUI = new BookTicketGUI(username);
        this.setVisible(false);
        bookTicketGUI.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void logOutButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButton1ActionPerformed
        // TODO add your handling code here:
        HomeGUI homeGUI = new HomeGUI();
        this.setVisible(false);
        homeGUI.setVisible(true);
    }//GEN-LAST:event_logOutButton1ActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        seattxt.setText("");
        
    }//GEN-LAST:event_resetButtonActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        // TODO add your handling code here:
        if(seattxt.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Select a seat");
        }
        else{
            name = nametxt.getText();
            seatno = Integer.parseInt(seattxt.getText());
            amount = Double.parseDouble(amttxt.getText());
            ticketno = ticket.newTicket(username, name, busId, amount, seatno,date);
            PrintTicketGUI printTicketGUI = new PrintTicketGUI(ticketno);
            this.setVisible(false);
            printTicketGUI.setVisible(true);
            
        }
        
    }//GEN-LAST:event_confirmButtonActionPerformed

    
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amtlbl;
    private javax.swing.JTextField amttxt;
    private javax.swing.JLabel arvltimelbl;
    private javax.swing.JTextField arvltimetxt;
    private javax.swing.JButton backButton;
    private javax.swing.JButton booktcktbtn;
    private javax.swing.JButton cncltcktbtn;
    private javax.swing.JButton confirmButton;
    private javax.swing.JLabel datelbl;
    private com.toedter.calendar.JDateChooser datetxt;
    private javax.swing.JLabel depttimelbl;
    private javax.swing.JTextField depttimetxt;
    private javax.swing.JLabel destlbl;
    private javax.swing.JTextField desttxt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton logOutButton1;
    private javax.swing.JLabel namelbl;
    private javax.swing.JTextField nametxt;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton retrivetcktbtn;
    private javax.swing.JLabel seatlbl;
    private javax.swing.JTextField seattxt;
    private javax.swing.JLabel srclbl;
    private javax.swing.JTextField srctxt;
    // End of variables declaration//GEN-END:variables
    
}
