/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Bus;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Anudeep
 */
public class EditRouteGUI extends javax.swing.JFrame {

    /**
     * Creates new form EditRouteGUI
     */
    String ausername;
    int routeId;
    String source;
    String destination;
    String arrivaltime;
    String depttime;
    double price;
    String narrivaltime;
    String ndepttime;
    double nprice;
    Bus bus = new Bus();
    public EditRouteGUI(String ausername,int routeId) {
        super("Edit Route");
        initComponents();
        //setSize(1350,730);
        this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        this.ausername = ausername;
        this.routeId = routeId;
        routeIDTxt.setText(Integer.toString(routeId));
        source = bus.getSource(routeId);
        srcTxt.setText(source);
        destination = bus.getDestination(routeId);
        destTXt.setText(destination);
        arrivaltime = bus.getArrivalTime(routeId);
        arrvlTxt.setText(arrivaltime);
        depttime = bus.getDepartureTime(routeId);
        deptTxt.setText(depttime);
        price = bus.getAmount(routeId);
        priceTxt.setText(Double.toString(price));
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        usermgtBtn = new javax.swing.JButton();
        routemgtBtn = new javax.swing.JButton();
        balancesheetBtn = new javax.swing.JButton();
        ticketSearchBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        editLbl = new javax.swing.JLabel();
        routeIDLbl = new javax.swing.JLabel();
        routeIDTxt = new javax.swing.JTextField();
        priceLbl = new javax.swing.JLabel();
        priceTxt = new javax.swing.JTextField();
        srcLbl = new javax.swing.JLabel();
        srcTxt = new javax.swing.JTextField();
        editBtn = new javax.swing.JButton();
        resetregbtn2 = new javax.swing.JButton();
        deptLbl = new javax.swing.JLabel();
        deptTxt = new javax.swing.JTextField();
        backbtn3 = new javax.swing.JButton();
        logOutButton1 = new javax.swing.JButton();
        destLbl = new javax.swing.JLabel();
        destTXt = new javax.swing.JTextField();
        arrvlLbl = new javax.swing.JLabel();
        arrvlTxt = new javax.swing.JTextField();
        deleteBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 700));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        usermgtBtn.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        usermgtBtn.setText("User Management");
        usermgtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usermgtBtnActionPerformed(evt);
            }
        });

        routemgtBtn.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        routemgtBtn.setText("Route Management");
        routemgtBtn.setEnabled(false);

        balancesheetBtn.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        balancesheetBtn.setText("Balance Sheet");
        balancesheetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balancesheetBtnActionPerformed(evt);
            }
        });

        ticketSearchBtn.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        ticketSearchBtn.setText("Ticket Search");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(usermgtBtn)
                .addGap(18, 18, 18)
                .addComponent(routemgtBtn)
                .addGap(18, 18, 18)
                .addComponent(balancesheetBtn)
                .addGap(18, 18, 18)
                .addComponent(ticketSearchBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usermgtBtn)
                    .addComponent(routemgtBtn)
                    .addComponent(balancesheetBtn)
                    .addComponent(ticketSearchBtn))
                .addGap(41, 41, 41))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        editLbl.setFont(new java.awt.Font("Times New Roman", 0, 35)); // NOI18N
        editLbl.setText("Edit/Delete Route");

        routeIDLbl.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        routeIDLbl.setText("Route ID");

        routeIDTxt.setEditable(false);
        routeIDTxt.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        routeIDTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                routeIDTxtActionPerformed(evt);
            }
        });

        priceLbl.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        priceLbl.setText("Price");

        priceTxt.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        priceTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceTxtActionPerformed(evt);
            }
        });

        srcLbl.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        srcLbl.setText("Source");

        srcTxt.setEditable(false);
        srcTxt.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        srcTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srcTxtActionPerformed(evt);
            }
        });

        editBtn.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        editBtn.setText("Edit");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        resetregbtn2.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        resetregbtn2.setText("Reset");
        resetregbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetregbtn2ActionPerformed(evt);
            }
        });

        deptLbl.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        deptLbl.setText("Departure Time");

        deptTxt.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        deptTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deptTxtActionPerformed(evt);
            }
        });

        backbtn3.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        backbtn3.setText("Back");
        backbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtn3ActionPerformed(evt);
            }
        });

        logOutButton1.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        logOutButton1.setText("Log Out");
        logOutButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButton1ActionPerformed(evt);
            }
        });

        destLbl.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        destLbl.setText("Destination");

        destTXt.setEditable(false);
        destTXt.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        destTXt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destTXtActionPerformed(evt);
            }
        });

        arrvlLbl.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        arrvlLbl.setText("Arrival Time");

        arrvlTxt.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        arrvlTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrvlTxtActionPerformed(evt);
            }
        });

        deleteBtn.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(editLbl)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(routeIDLbl)
                            .addComponent(srcLbl)
                            .addComponent(destLbl))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(resetregbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(backbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(routeIDTxt)
                                    .addComponent(srcTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                                    .addComponent(destTXt, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(deptLbl)
                                    .addComponent(priceLbl)
                                    .addComponent(arrvlLbl))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(priceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(deptTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(arrvlTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logOutButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(editLbl)
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(routeIDLbl)
                    .addComponent(routeIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceLbl)
                    .addComponent(priceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(srcLbl)
                    .addComponent(srcTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deptLbl)
                    .addComponent(deptTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(destTXt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(arrvlLbl)
                        .addComponent(arrvlTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(destLbl))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(resetregbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logOutButton1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void routeIDTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_routeIDTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_routeIDTxtActionPerformed

    private void priceTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceTxtActionPerformed

    private void srcTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srcTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_srcTxtActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        // TODO add your handling code here:
        narrivaltime = arrvlTxt.getText();
        ndepttime = deptTxt.getText();
        nprice = Double.parseDouble(priceTxt.getText());
        if(arrivaltime.equals(narrivaltime)&&depttime.equals(ndepttime)&&price==nprice){
            JOptionPane.showMessageDialog(this, "Change atleast one parameter");
        }
        else if(narrivaltime.equals("")||ndepttime.equals("")||nprice==0.00){
            JOptionPane.showMessageDialog(this, "All fields are mandatory");
        }
        
        else{
            bus.updateRoute(routeId, narrivaltime, ndepttime, nprice);
            JOptionPane.showMessageDialog(this, "Route details updated");
            AdminRouteMgtGUI adminRouteMgtGUI = new AdminRouteMgtGUI(ausername);
            this.setVisible(false);
            adminRouteMgtGUI.setVisible(true);
        }
                
        
    }//GEN-LAST:event_editBtnActionPerformed

    private void resetregbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetregbtn2ActionPerformed
        // TODO add your handling code here:
        arrvlTxt.setText(arrivaltime);
        deptTxt.setText(depttime);
        priceTxt.setText(Double.toString(price));
    }//GEN-LAST:event_resetregbtn2ActionPerformed

    private void deptTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deptTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deptTxtActionPerformed

    private void backbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtn3ActionPerformed
        // TODO add your handling code here:
        AdminRouteMgtGUI adminRouteMgtGUI = new AdminRouteMgtGUI(ausername);
        this.setVisible(false);
        adminRouteMgtGUI.setVisible(true);
    }//GEN-LAST:event_backbtn3ActionPerformed

    private void logOutButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButton1ActionPerformed
        // TODO add your handling code here:
        AdminLoginGUI adminLoginGUI = new AdminLoginGUI();
        this.setVisible(false);
        adminLoginGUI.setVisible(true);
    }//GEN-LAST:event_logOutButton1ActionPerformed

    private void destTXtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destTXtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destTXtActionPerformed

    private void arrvlTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrvlTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arrvlTxtActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        bus.deleteRoute(routeId);
        JOptionPane.showMessageDialog(this, "Route deleted sucessfully");
        AdminRouteMgtGUI adminRouteMgtGUI = new AdminRouteMgtGUI(ausername);
        this.setVisible(false);
        adminRouteMgtGUI.setVisible(true);

    }//GEN-LAST:event_deleteBtnActionPerformed

    private void usermgtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usermgtBtnActionPerformed
        // TODO add your handling code here:
        AdminUserMgtGUI adminUserMgtGUI = new AdminUserMgtGUI(ausername);
        this.setVisible(false);
        adminUserMgtGUI.setVisible(true);
    }//GEN-LAST:event_usermgtBtnActionPerformed

    private void balancesheetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balancesheetBtnActionPerformed
        // TODO add your handling code here:
        BalanceSheetGUI balanceSheetGUI = new BalanceSheetGUI(ausername);
        this.setVisible(false);
        balanceSheetGUI.setVisible(true);
    }//GEN-LAST:event_balancesheetBtnActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arrvlLbl;
    private javax.swing.JTextField arrvlTxt;
    private javax.swing.JButton backbtn3;
    private javax.swing.JButton balancesheetBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel deptLbl;
    private javax.swing.JTextField deptTxt;
    private javax.swing.JLabel destLbl;
    private javax.swing.JTextField destTXt;
    private javax.swing.JButton editBtn;
    private javax.swing.JLabel editLbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton logOutButton1;
    private javax.swing.JLabel priceLbl;
    private javax.swing.JTextField priceTxt;
    private javax.swing.JButton resetregbtn2;
    private javax.swing.JLabel routeIDLbl;
    private javax.swing.JTextField routeIDTxt;
    private javax.swing.JButton routemgtBtn;
    private javax.swing.JLabel srcLbl;
    private javax.swing.JTextField srcTxt;
    private javax.swing.JButton ticketSearchBtn;
    private javax.swing.JButton usermgtBtn;
    // End of variables declaration//GEN-END:variables
}
