/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Home;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Anudeep
 */
public class EditUserGUI extends javax.swing.JFrame {

    /**
     * Creates new form EditUserGUI
     */
    String ausername;
    String username;
    String phone;
    String emailId;
    String name;
    String nphone;
    String nemailId;
    String nname;
    String message;
    Home home = new Home();
    public EditUserGUI(String ausername,String username) {
        super("Edit User");
        initComponents();
        //setSize(1350,730);
        this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        this.ausername = ausername;
        this.username = username;
        usernameregtxt2.setText(username);
        phone = home.getPhone(username);
        phnregtxt2.setText(phone);
        name = home.getName(username);
        nameregtxt2.setText(name);
        emailId = home.getEmailId(username);
        emailidregtxt2.setText(emailId);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        usermgtBtn = new javax.swing.JButton();
        routemgtBtn = new javax.swing.JButton();
        balanceshtBtn = new javax.swing.JButton();
        ticketSearchBtn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        editLbl = new javax.swing.JLabel();
        usernameReglbl2 = new javax.swing.JLabel();
        usernameregtxt2 = new javax.swing.JTextField();
        emailidreglbl2 = new javax.swing.JLabel();
        emailidregtxt2 = new javax.swing.JTextField();
        nameredlbl2 = new javax.swing.JLabel();
        nameregtxt2 = new javax.swing.JTextField();
        editBtn = new javax.swing.JButton();
        resetregbtn2 = new javax.swing.JButton();
        phnreglbl2 = new javax.swing.JLabel();
        backbtn3 = new javax.swing.JButton();
        logOutButton1 = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        phnregtxt2 = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 700));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        usermgtBtn.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        usermgtBtn.setText("User Management");
        usermgtBtn.setEnabled(false);

        routemgtBtn.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        routemgtBtn.setText("Route Management");
        routemgtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                routemgtBtnActionPerformed(evt);
            }
        });

        balanceshtBtn.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        balanceshtBtn.setText("Balance Sheet");
        balanceshtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balanceshtBtnActionPerformed(evt);
            }
        });

        ticketSearchBtn.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        ticketSearchBtn.setText("Ticket Search");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(usermgtBtn)
                .addGap(18, 18, 18)
                .addComponent(routemgtBtn)
                .addGap(18, 18, 18)
                .addComponent(balanceshtBtn)
                .addGap(18, 18, 18)
                .addComponent(ticketSearchBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usermgtBtn)
                    .addComponent(routemgtBtn)
                    .addComponent(balanceshtBtn)
                    .addComponent(ticketSearchBtn))
                .addGap(41, 41, 41))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        editLbl.setFont(new java.awt.Font("Times New Roman", 0, 35)); // NOI18N
        editLbl.setText("Edit User Details");

        usernameReglbl2.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        usernameReglbl2.setText("Username");

        usernameregtxt2.setEditable(false);
        usernameregtxt2.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        usernameregtxt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameregtxt2ActionPerformed(evt);
            }
        });

        emailidreglbl2.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        emailidreglbl2.setText("Email ID");

        emailidregtxt2.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        emailidregtxt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailidregtxt2ActionPerformed(evt);
            }
        });

        nameredlbl2.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        nameredlbl2.setText("Name");

        nameregtxt2.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        nameregtxt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameregtxt2ActionPerformed(evt);
            }
        });

        editBtn.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        editBtn.setText("Edit");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        resetregbtn2.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        resetregbtn2.setText("Reset");
        resetregbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetregbtn2ActionPerformed(evt);
            }
        });

        phnreglbl2.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        phnreglbl2.setText("Phone");

        backbtn3.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        backbtn3.setText("Back");
        backbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtn3ActionPerformed(evt);
            }
        });

        logOutButton1.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        logOutButton1.setText("Log Out");
        logOutButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButton1ActionPerformed(evt);
            }
        });

        deleteBtn.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        phnregtxt2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        phnregtxt2.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        phnregtxt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phnregtxt2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(editLbl)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(usernameReglbl2)
                                    .addComponent(nameredlbl2))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(usernameregtxt2)
                                    .addComponent(nameregtxt2, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE))
                                .addGap(32, 32, 32))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(emailidreglbl2)
                                    .addComponent(phnreglbl2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(emailidregtxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(phnregtxt2)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(resetregbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(backbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logOutButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(editLbl)
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameReglbl2)
                    .addComponent(usernameregtxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailidreglbl2)
                    .addComponent(emailidregtxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameredlbl2)
                    .addComponent(nameregtxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phnreglbl2)
                    .addComponent(phnregtxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetregbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(logOutButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameregtxt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameregtxt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameregtxt2ActionPerformed

    private void emailidregtxt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailidregtxt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailidregtxt2ActionPerformed

    private void nameregtxt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameregtxt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameregtxt2ActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        // TODO add your handling code here:
        nemailId = emailidregtxt2.getText();
        nphone = phnregtxt2.getText();
        nname = nameregtxt2.getText();
        if(emailId.equals(nemailId)&&phone.equals(nphone)&&name.equals(nname)){
            JOptionPane.showMessageDialog(this, "Change atleast one parameter");
        }
        else if(nemailId.equals("")||nname.equals("")||nphone.equals("")){
            JOptionPane.showMessageDialog(this, "All fields are mandatory");
        }
        else if(!nemailId.contains("@")||!nemailId.contains(".")){
            JOptionPane.showMessageDialog(this, "Enter a valid email ID");
        }
        else{
            home.updateUserDetails(username, nname, nemailId, nphone);
            JOptionPane.showMessageDialog(this, "User details updated");
            AdminUserMgtGUI adminUserMgtGUI = new AdminUserMgtGUI(ausername);
            this.setVisible(false);
            adminUserMgtGUI.setVisible(true);
        }
    }//GEN-LAST:event_editBtnActionPerformed

    private void resetregbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetregbtn2ActionPerformed
        // TODO add your handling code here:
        emailidregtxt2.setText(emailId);
        phnregtxt2.setText(phone);
        nameregtxt2.setText(name);
        
    }//GEN-LAST:event_resetregbtn2ActionPerformed

    private void backbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtn3ActionPerformed
        // TODO add your handling code here:
        AdminUserMgtGUI adminUserMgtGUI = new AdminUserMgtGUI(ausername);
        this.setVisible(false);
        adminUserMgtGUI.setVisible(true);
    }//GEN-LAST:event_backbtn3ActionPerformed

    private void logOutButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButton1ActionPerformed
        // TODO add your handling code here:
        AdminLoginGUI adminLoginGUI = new AdminLoginGUI();
        this.setVisible(false);
        adminLoginGUI.setVisible(true);
    }//GEN-LAST:event_logOutButton1ActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        message = home.deleteUser(username);
        if(message == "User is Deleted"){
            JOptionPane.showMessageDialog(this, "User deleted sucessfully");
            AdminUserMgtGUI adminUserMgtGUI = new AdminUserMgtGUI(ausername);
            this.setVisible(false);
            adminUserMgtGUI.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(this, "User cannct be deleted, check for active tickets or User doesnot exsits");
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void routemgtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_routemgtBtnActionPerformed
        // TODO add your handling code here:
        AdminRouteMgtGUI adminRouteMgtGUI = new AdminRouteMgtGUI(ausername);
        this.setVisible(false);
        adminRouteMgtGUI.setVisible(true);
    }//GEN-LAST:event_routemgtBtnActionPerformed

    private void balanceshtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balanceshtBtnActionPerformed
        // TODO add your handling code here:
        BalanceSheetGUI balanceSheetGUI = new BalanceSheetGUI(ausername);
        this.setVisible(false);
        balanceSheetGUI.setVisible(true);
    }//GEN-LAST:event_balanceshtBtnActionPerformed

    private void phnregtxt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phnregtxt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phnregtxt2ActionPerformed


    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn3;
    private javax.swing.JButton balanceshtBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JLabel editLbl;
    private javax.swing.JLabel emailidreglbl2;
    private javax.swing.JTextField emailidregtxt2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton logOutButton1;
    private javax.swing.JLabel nameredlbl2;
    private javax.swing.JTextField nameregtxt2;
    private javax.swing.JLabel phnreglbl2;
    private javax.swing.JFormattedTextField phnregtxt2;
    private javax.swing.JButton resetregbtn2;
    private javax.swing.JButton routemgtBtn;
    private javax.swing.JButton ticketSearchBtn;
    private javax.swing.JButton usermgtBtn;
    private javax.swing.JLabel usernameReglbl2;
    private javax.swing.JTextField usernameregtxt2;
    // End of variables declaration//GEN-END:variables
}
