/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Home;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Anudeep
 */
public class HomeGUI extends javax.swing.JFrame {

    /**
     * Creates new form HomeGUI
     */
    String username;
    String password;
    String cpassword;
    String emailID;
    String phone;
    String name;
    Home home = new Home();
    public HomeGUI() {
        super("Home");
        initComponents();
        //setSize(1350, 730);
        this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mainLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        loginLabel = new javax.swing.JLabel();
        usernameLoginLabel = new javax.swing.JLabel();
        usernameLoginText = new javax.swing.JTextField();
        passwordLoginLabel = new javax.swing.JLabel();
        passwordLoginText = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        resetLoginButton = new javax.swing.JButton();
        adminLoginbtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        registerLabel = new javax.swing.JLabel();
        usernameReglbl = new javax.swing.JLabel();
        usernameregtxt = new javax.swing.JTextField();
        pwdreglbl = new javax.swing.JLabel();
        cpwdreglbl = new javax.swing.JLabel();
        emailidreglbl = new javax.swing.JLabel();
        emailidregtxt = new javax.swing.JTextField();
        nameredlbl = new javax.swing.JLabel();
        nameregtxt = new javax.swing.JTextField();
        regBtn = new javax.swing.JButton();
        resetregbtn = new javax.swing.JButton();
        phnreglbl = new javax.swing.JLabel();
        pwdregtxt = new javax.swing.JPasswordField();
        cpwdregtxt = new javax.swing.JPasswordField();
        phnregtxt = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 700));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        mainLabel.setFont(new java.awt.Font("Times New Roman", 3, 96)); // NOI18N
        mainLabel.setText("Online Bus Reservation");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(mainLabel)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        loginLabel.setFont(new java.awt.Font("Times New Roman", 0, 35)); // NOI18N
        loginLabel.setText("Login");

        usernameLoginLabel.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        usernameLoginLabel.setText("Username");

        usernameLoginText.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        usernameLoginText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameLoginTextActionPerformed(evt);
            }
        });

        passwordLoginLabel.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        passwordLoginLabel.setText("Password");

        passwordLoginText.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        passwordLoginText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordLoginTextActionPerformed(evt);
            }
        });

        loginButton.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        resetLoginButton.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        resetLoginButton.setText("Reset");
        resetLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetLoginButtonActionPerformed(evt);
            }
        });

        adminLoginbtn.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        adminLoginbtn.setText("Admin Login");
        adminLoginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminLoginbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(resetLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(loginLabel)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usernameLoginLabel)
                            .addComponent(passwordLoginLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usernameLoginText)
                            .addComponent(passwordLoginText, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))))
                .addContainerGap(192, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(adminLoginbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(loginLabel)
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLoginLabel)
                    .addComponent(usernameLoginText, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(passwordLoginLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(passwordLoginText))
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(adminLoginbtn)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        registerLabel.setFont(new java.awt.Font("Times New Roman", 0, 35)); // NOI18N
        registerLabel.setText("Register");

        usernameReglbl.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        usernameReglbl.setText("Username");

        usernameregtxt.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        usernameregtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameregtxtActionPerformed(evt);
            }
        });

        pwdreglbl.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        pwdreglbl.setText("Password");

        cpwdreglbl.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        cpwdreglbl.setText("Confirm Password");

        emailidreglbl.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        emailidreglbl.setText("Email ID");

        emailidregtxt.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        emailidregtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailidregtxtActionPerformed(evt);
            }
        });

        nameredlbl.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        nameredlbl.setText("Name");

        nameregtxt.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        nameregtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameregtxtActionPerformed(evt);
            }
        });

        regBtn.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        regBtn.setText("Register");
        regBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regBtnActionPerformed(evt);
            }
        });

        resetregbtn.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        resetregbtn.setText("Reset");
        resetregbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetregbtnActionPerformed(evt);
            }
        });

        phnreglbl.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        phnreglbl.setText("Phone");

        pwdregtxt.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N

        cpwdregtxt.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N

        phnregtxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        phnregtxt.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        phnregtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phnregtxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(cpwdreglbl)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(registerLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(usernameReglbl)
                            .addComponent(pwdreglbl))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(regBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(resetregbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(163, 163, 163))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(98, 98, 98)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(usernameregtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(pwdregtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(97, 97, 97)
                                        .addComponent(cpwdregtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameredlbl)
                                    .addComponent(emailidreglbl)
                                    .addComponent(phnreglbl))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(emailidregtxt, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                                    .addComponent(nameregtxt)
                                    .addComponent(phnregtxt))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(19, 19, 19))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(registerLabel)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(usernameReglbl)
                            .addComponent(usernameregtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameredlbl)
                            .addComponent(nameregtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pwdreglbl)
                            .addComponent(emailidreglbl)
                            .addComponent(emailidregtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(pwdregtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpwdreglbl)
                    .addComponent(phnreglbl)
                    .addComponent(cpwdregtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phnregtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetregbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameLoginTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameLoginTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameLoginTextActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        username = usernameLoginText.getText();
        password = passwordLoginText.getText();
        
            
            if(!username.equals("")&&!password.equals("")&&password.equals(home.login(username))){
                BookTicketGUI bookTicketGUI = new BookTicketGUI(username);
                this.setVisible(false);
                bookTicketGUI.setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(this, "Enter valid Username or password.");
            }
       
        
    }//GEN-LAST:event_loginButtonActionPerformed

    private void resetLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetLoginButtonActionPerformed
        // TODO add your handling code here:
        usernameLoginText.setText("");
        passwordLoginText.setText("");
    }//GEN-LAST:event_resetLoginButtonActionPerformed

    private void adminLoginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminLoginbtnActionPerformed
        // TODO add your handling code here:
        AdminLoginGUI adminLoginGUI = new AdminLoginGUI();
        this.setVisible(false);
        adminLoginGUI.setVisible(true);
    }//GEN-LAST:event_adminLoginbtnActionPerformed

    private void resetregbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetregbtnActionPerformed
        // TODO add your handling code here:
        emailidregtxt.setText("");
        nameregtxt.setText("");
        phnregtxt.setText("");
        usernameregtxt.setText("");
        pwdregtxt.setText("");
        cpwdregtxt.setText("");
        
    }//GEN-LAST:event_resetregbtnActionPerformed

    private void regBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regBtnActionPerformed
        // TODO add your handling code here:
        username = usernameregtxt.getText();
        password = pwdregtxt.getText();
        cpassword = cpwdregtxt.getText();
        phone = phnregtxt.getText();
        name = nameregtxt.getText();
        emailID = emailidregtxt.getText();
        
        if(username.equals("")){
           JOptionPane.showMessageDialog(this, "Enter valid Username");
        } 
        
        else if(password.equals("")){
           JOptionPane.showMessageDialog(this, "Enter valid password");
        }
        
        else if(cpassword.equals("")){
           JOptionPane.showMessageDialog(this, "Enter valid password");
        } 
        
        else if(phone.equals("")){
           JOptionPane.showMessageDialog(this, "Enter valid phone number");
        } 
        
        else if(name.equals("")){
           JOptionPane.showMessageDialog(this, "Enter valid name");
        } 
        
        else if(emailID.equals("")||!emailID.contains("@")||!emailID.contains(".")){
            JOptionPane.showMessageDialog(this, "Enter valid emailID");
        }
        
        else if(!password.equals(cpassword)){
            JOptionPane.showMessageDialog(this, "Both passwords should match");
        }
        
        else{
            String message;
            message = home.register(username, password, name, emailID, phone);
            if(message.equals("User created")){           
                JOptionPane.showMessageDialog(this, "User Created Successfully");
                BookTicketGUI bookTicketGUI = new BookTicketGUI(username);
                this.setVisible(false);
                bookTicketGUI.setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(this, "User already exists");
            }
        }
        
        
       
        
        
    }//GEN-LAST:event_regBtnActionPerformed

    private void nameregtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameregtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameregtxtActionPerformed

    private void emailidregtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailidregtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailidregtxtActionPerformed

    private void usernameregtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameregtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameregtxtActionPerformed

    private void passwordLoginTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordLoginTextActionPerformed
        // TODO add your handling code here:
        loginButtonActionPerformed(evt);
    }//GEN-LAST:event_passwordLoginTextActionPerformed

    private void phnregtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phnregtxtActionPerformed
        // TODO add your handling code here:
        regBtnActionPerformed(evt);
    }//GEN-LAST:event_phnregtxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminLoginbtn;
    private javax.swing.JLabel cpwdreglbl;
    private javax.swing.JPasswordField cpwdregtxt;
    private javax.swing.JLabel emailidreglbl;
    private javax.swing.JTextField emailidregtxt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JLabel mainLabel;
    private javax.swing.JLabel nameredlbl;
    private javax.swing.JTextField nameregtxt;
    private javax.swing.JLabel passwordLoginLabel;
    private javax.swing.JPasswordField passwordLoginText;
    private javax.swing.JLabel phnreglbl;
    private javax.swing.JFormattedTextField phnregtxt;
    private javax.swing.JLabel pwdreglbl;
    private javax.swing.JPasswordField pwdregtxt;
    private javax.swing.JButton regBtn;
    private javax.swing.JLabel registerLabel;
    private javax.swing.JButton resetLoginButton;
    private javax.swing.JButton resetregbtn;
    private javax.swing.JLabel usernameLoginLabel;
    private javax.swing.JTextField usernameLoginText;
    private javax.swing.JLabel usernameReglbl;
    private javax.swing.JTextField usernameregtxt;
    // End of variables declaration//GEN-END:variables
}
