/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Bus;
import Model.Ticket;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import javax.swing.JFrame;

/**
 *
 * @author Anudeep
 */
public class PrintTicketGUI extends javax.swing.JFrame {

    /**
     * Creates new form PrintTicketGUI
     */
    Bus bus = new Bus();
    Ticket ticket = new Ticket();
    int busId;
    public PrintTicketGUI(int ticketno) {
        super("Print Ticket");
        initComponents();
        //setSize(1350,730);
        this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        
        tcktidtxt.setText(Integer.toString(ticketno));
        nametxt.setText(ticket.getName(ticketno));
        amttxt.setText(Double.toString(ticket.getAmount(ticketno)));
        seattxt.setText(Integer.toString(ticket.getSeatno(ticketno)));
        datetxt.setDate(ticket.getDate(ticketno));
        busId = ticket.getBusID(ticketno);
        srctxt.setText(bus.getSource(busId));
        desttxt.setText(bus.getDestination(busId));
        arvltimetxt.setText(bus.getArrivalTime(busId));
        depttimetxt.setText(bus.getDepartureTime(busId));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mainLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        srclbl = new javax.swing.JLabel();
        srctxt = new javax.swing.JTextField();
        depttimetxt = new javax.swing.JTextField();
        depttimelbl = new javax.swing.JLabel();
        destlbl = new javax.swing.JLabel();
        desttxt = new javax.swing.JTextField();
        arvltimelbl = new javax.swing.JLabel();
        arvltimetxt = new javax.swing.JTextField();
        datelbl = new javax.swing.JLabel();
        namelbl = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        amtlbl = new javax.swing.JLabel();
        amttxt = new javax.swing.JTextField();
        seatlbl = new javax.swing.JLabel();
        seattxt = new javax.swing.JTextField();
        printBtn = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();
        tcktidlbl = new javax.swing.JLabel();
        tcktidtxt = new javax.swing.JTextField();
        datetxt = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 700));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        mainLabel.setFont(new java.awt.Font("Times New Roman", 3, 96)); // NOI18N
        mainLabel.setText("Ticket");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(mainLabel)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        srclbl.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        srclbl.setText("Source");

        srctxt.setEditable(false);
        srctxt.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        srctxt.setBorder(null);
        srctxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srctxtActionPerformed(evt);
            }
        });

        depttimetxt.setEditable(false);
        depttimetxt.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        depttimetxt.setBorder(null);
        depttimetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depttimetxtActionPerformed(evt);
            }
        });

        depttimelbl.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        depttimelbl.setText("Departure Time");

        destlbl.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        destlbl.setText("Destination");

        desttxt.setEditable(false);
        desttxt.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        desttxt.setBorder(null);
        desttxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desttxtActionPerformed(evt);
            }
        });

        arvltimelbl.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        arvltimelbl.setText("Arrival Time");

        arvltimetxt.setEditable(false);
        arvltimetxt.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        arvltimetxt.setBorder(null);
        arvltimetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arvltimetxtActionPerformed(evt);
            }
        });

        datelbl.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        datelbl.setText("Date");

        namelbl.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        namelbl.setText("Name");

        nametxt.setEditable(false);
        nametxt.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        nametxt.setBorder(null);
        nametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nametxtActionPerformed(evt);
            }
        });

        amtlbl.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        amtlbl.setText("Amount");

        amttxt.setEditable(false);
        amttxt.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        amttxt.setBorder(null);
        amttxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amttxtActionPerformed(evt);
            }
        });

        seatlbl.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        seatlbl.setText("Seat");

        seattxt.setEditable(false);
        seattxt.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        seattxt.setBorder(null);
        seattxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seattxtActionPerformed(evt);
            }
        });

        printBtn.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        printBtn.setText("Print");
        printBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printBtnActionPerformed(evt);
            }
        });

        homeBtn.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        homeBtn.setText("Home");
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        tcktidlbl.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        tcktidlbl.setText("Ticket ID");

        tcktidtxt.setEditable(false);
        tcktidtxt.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        tcktidtxt.setBorder(null);
        tcktidtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcktidtxtActionPerformed(evt);
            }
        });

        datetxt.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(printBtn)
                        .addGap(18, 18, 18)
                        .addComponent(homeBtn))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(srclbl, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(destlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(datelbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(amtlbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(tcktidlbl)
                                .addGap(36, 36, 36)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tcktidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(desttxt)
                            .addComponent(srctxt)
                            .addComponent(amttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(datetxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(arvltimelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(depttimelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(namelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seatlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(arvltimetxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(nametxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(seattxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(depttimetxt))
                        .addGap(0, 40, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tcktidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tcktidlbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(srclbl)
                    .addComponent(srctxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(depttimelbl)
                    .addComponent(depttimetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(destlbl)
                    .addComponent(desttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(arvltimelbl)
                    .addComponent(arvltimetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(datetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(namelbl)
                        .addComponent(datelbl)
                        .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatlbl)
                    .addComponent(seattxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amtlbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(printBtn)
                    .addComponent(homeBtn))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void srctxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srctxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_srctxtActionPerformed

    private void depttimetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depttimetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_depttimetxtActionPerformed

    private void desttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desttxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desttxtActionPerformed

    private void arvltimetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arvltimetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arvltimetxtActionPerformed

    private void nametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nametxtActionPerformed

    private void amttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amttxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amttxtActionPerformed

    private void seattxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seattxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seattxtActionPerformed

    private void printBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printBtnActionPerformed
        // TODO add your handling code here:
        PrinterJob job = PrinterJob.getPrinterJob();
        job.setJobName("Print Data");

        job.setPrintable(new Printable() {
            public int print(Graphics pg, PageFormat pf, int pageNum) {
                pf.setOrientation(PageFormat.LANDSCAPE);
                if (pageNum > 0) {
                    return Printable.NO_SUCH_PAGE;
                }
                Graphics2D g2 = (Graphics2D) pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                g2.scale(0.75, 0.75);
                jPanel2.paint(pg);
                return Printable.PAGE_EXISTS;
            }
        });
        boolean flag = job.printDialog();
        if (flag) {
            try {
                job.print();
            } catch (PrinterException ex) {
            }
        }
    }//GEN-LAST:event_printBtnActionPerformed

    private void tcktidtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcktidtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tcktidtxtActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        // TODO add your handling code here:
        HomeGUI homeGUI = new HomeGUI();
        this.setVisible(false);
        homeGUI.setVisible(true);
    }//GEN-LAST:event_homeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amtlbl;
    private javax.swing.JTextField amttxt;
    private javax.swing.JLabel arvltimelbl;
    private javax.swing.JTextField arvltimetxt;
    private javax.swing.JLabel datelbl;
    private com.toedter.calendar.JDateChooser datetxt;
    private javax.swing.JLabel depttimelbl;
    private javax.swing.JTextField depttimetxt;
    private javax.swing.JLabel destlbl;
    private javax.swing.JTextField desttxt;
    private javax.swing.JButton homeBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel mainLabel;
    private javax.swing.JLabel namelbl;
    private javax.swing.JTextField nametxt;
    private javax.swing.JButton printBtn;
    private javax.swing.JLabel seatlbl;
    private javax.swing.JTextField seattxt;
    private javax.swing.JLabel srclbl;
    private javax.swing.JTextField srctxt;
    private javax.swing.JLabel tcktidlbl;
    private javax.swing.JTextField tcktidtxt;
    // End of variables declaration//GEN-END:variables
}
